import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { TRPCReactProvider } from "@/trpc/client";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@components/ui/sonner";

const agenorSans = localFont({
    src: "../styles/fonts/AgenorNeue-Regular.otf",
    variable: "--font-agenor-sans",
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider afterSignOutUrl={"/"}>
            <html
                lang="en"
                className={`${geistSans.variable} ${geistMono.variable} ${agenorSans.variable} antialiased`}
            >
                <body>
                    <NuqsAdapter>
                        <TRPCReactProvider>{children}</TRPCReactProvider>
                        <Toaster />
                    </NuqsAdapter>
                </body>
            </html>
        </ClerkProvider>
    );
}
